### ISSUE TITLE
WPF Asp.net

### ISSUE THREAD

**Issue by matthiasschalhas** [rstropek-teaching/bike-rental-ui-quiz-5ahif-matthiasschalhas#1]
Wie verwendet man wpf mit asp.net core?
Wie ist das genau gemeint?

**Comment by rstropek** [comment]
Hi @matthiasschalhas 

Unfortunately, this is not possible. WPF does *not* work with .NET Core. You have to use .NET 4.x Full Framework instead. .NET Core is only possible with UWP and Xamarin.

Greetings,
Rainer Stropek.
